var tree = [["[Global Namespace]",,"",
                [["SplClassLoader","SplClassLoader.html","",
                [        ]]        ]],["Assets","Assets.html","",
                [["Autoload","Assets\/Autoload.html","",
                [["AssetsAutoloaderGenerator","Assets\/Autoload\/AssetsAutoloaderGenerator.html","",
                [        ]]        ]],["Util","Assets\/Util.html","",
                [["Filesystem","Assets\/Util\/Filesystem.html"," < Filesystem",
                [        ]]        ]],["ComposerInstaller","Assets\/ComposerInstaller.html"," < AutoloadGenerator",
                [        ]],["Loader","Assets\/Loader.html","",
                [        ]]        ]],["TemplateEngine","TemplateEngine.html","",
                [["MinifierAdapter","TemplateEngine\/MinifierAdapter.html","",
                [["CSS","TemplateEngine\/MinifierAdapter\/CSS.html"," < AbstractMinifierAdapter",
                [        ]],["JS","TemplateEngine\/MinifierAdapter\/JS.html"," < AbstractMinifierAdapter",
                [        ]]        ]],["TemplateObject","TemplateEngine\/TemplateObject.html","",
                [["Abstracts","TemplateEngine\/TemplateObject\/Abstracts.html","",
                [["AbstractFileTemplateObject","TemplateEngine\/TemplateObject\/Abstracts\/AbstractFileTemplateObject.html"," < AbstractTemplateObject",
                [        ]],["AbstractTemplateObject","TemplateEngine\/TemplateObject\/Abstracts\/AbstractTemplateObject.html","",
                [        ]],["FileTemplateObjectInterface","TemplateEngine\/TemplateObject\/Abstracts\/FileTemplateObjectInterface.html","",
                [        ]],["TemplateObjectInterface","TemplateEngine\/TemplateObject\/Abstracts\/TemplateObjectInterface.html","",
                [        ]]        ]],["CssFile","TemplateEngine\/TemplateObject\/CssFile.html"," < AbstractFileTemplateObject",
                [        ]],["JavascriptFile","TemplateEngine\/TemplateObject\/JavascriptFile.html"," < AbstractFileTemplateObject",
                [        ]],["JavascriptTag","TemplateEngine\/TemplateObject\/JavascriptTag.html"," < AbstractTemplateObject",
                [        ]],["LinkTag","TemplateEngine\/TemplateObject\/LinkTag.html"," < AbstractTemplateObject",
                [        ]],["MetaTag","TemplateEngine\/TemplateObject\/MetaTag.html"," < AbstractTemplateObject",
                [        ]],["TitleTag","TemplateEngine\/TemplateObject\/TitleTag.html"," < AbstractTemplateObject",
                [        ]]        ]],["AbstractMinifierAdapter","TemplateEngine\/AbstractMinifierAdapter.html","",
                [        ]],["Minifier","TemplateEngine\/Minifier.html","",
                [        ]],["Template","TemplateEngine\/Template.html","",
                [        ]],["TemplateEngine","TemplateEngine\/TemplateEngine.html"," < AbstractSingleton",
                [        ]],["TemplateEngineException","TemplateEngine\/TemplateEngineException.html"," < Exception",
                [        ]],["View","TemplateEngine\/View.html"," < AbstractView",
                [        ]]        ]]        ]

