var tree = [["[Global Namespace]",,"",
                [["SplClassLoader","SplClassLoader.html","",
                [        ]]        ]],["Assets","Assets.html","",
                [["Composer","Assets\/Composer.html","",
                [["TemplateEngineAutoloadGenerator","Assets\/Composer\/TemplateEngineAutoloadGenerator.html"," < AutoloadGenerator",
                [        ]],["TemplateEngineConfig","Assets\/Composer\/TemplateEngineConfig.html"," < DefaultConfig",
                [        ]],["TemplateEngineInstaller","Assets\/Composer\/TemplateEngineInstaller.html","",
                [        ]]        ]],["CompressorAdapter","Assets\/CompressorAdapter.html","",
                [["CSS","Assets\/CompressorAdapter\/CSS.html"," < AbstractCompressorAdapter",
                [        ]],["JS","Assets\/CompressorAdapter\/JS.html"," < AbstractCompressorAdapter",
                [        ]]        ]],["Package","Assets\/Package.html","",
                [["Package","Assets\/Package\/Package.html"," < AssetsPackage",
                [        ]],["Preset","Assets\/Package\/Preset.html"," < Preset",
                [        ]]        ]],["AbstractCompressorAdapter","Assets\/AbstractCompressorAdapter.html","",
                [        ]],["AssetNotFoundException","Assets\/AssetNotFoundException.html"," < Exception",
                [        ]],["Compressor","Assets\/Compressor.html","",
                [        ]],["Loader","Assets\/Loader.html"," < Loader",
                [        ]],["TemplateEngineConfig","Assets\/TemplateEngineConfig.html","",
                [        ]]        ]],["TemplateEngine","TemplateEngine.html","",
                [["TemplateObject","TemplateEngine\/TemplateObject.html","",
                [["Abstracts","TemplateEngine\/TemplateObject\/Abstracts.html","",
                [["AbstractFileTemplateObject","TemplateEngine\/TemplateObject\/Abstracts\/AbstractFileTemplateObject.html"," < AbstractTemplateObject",
                [        ]],["AbstractTemplateObject","TemplateEngine\/TemplateObject\/Abstracts\/AbstractTemplateObject.html","",
                [        ]],["FileTemplateObjectInterface","TemplateEngine\/TemplateObject\/Abstracts\/FileTemplateObjectInterface.html","",
                [        ]],["TemplateObjectInterface","TemplateEngine\/TemplateObject\/Abstracts\/TemplateObjectInterface.html","",
                [        ]]        ]],["CssFile","TemplateEngine\/TemplateObject\/CssFile.html"," < AbstractFileTemplateObject",
                [        ]],["CssTag","TemplateEngine\/TemplateObject\/CssTag.html"," < AbstractTemplateObject",
                [        ]],["JavascriptFile","TemplateEngine\/TemplateObject\/JavascriptFile.html"," < AbstractFileTemplateObject",
                [        ]],["JavascriptTag","TemplateEngine\/TemplateObject\/JavascriptTag.html"," < AbstractTemplateObject",
                [        ]],["LinkTag","TemplateEngine\/TemplateObject\/LinkTag.html"," < AbstractTemplateObject",
                [        ]],["MetaTag","TemplateEngine\/TemplateObject\/MetaTag.html"," < AbstractTemplateObject",
                [        ]],["TitleTag","TemplateEngine\/TemplateObject\/TitleTag.html"," < AbstractTemplateObject",
                [        ]]        ]],["Template","TemplateEngine\/Template.html","",
                [        ]],["TemplateEngine","TemplateEngine\/TemplateEngine.html"," < AbstractSingleton",
                [        ]],["TemplateEngineException","TemplateEngine\/TemplateEngineException.html"," < Exception",
                [        ]],["View","TemplateEngine\/View.html"," < AbstractView",
                [        ]]        ]]        ]

